/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as OptimizationRouteImport } from './routes/optimization'
import { Route as GovernRouteImport } from './routes/govern'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as ChargebackRouteImport } from './routes/chargeback'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GovernPartnersRouteImport } from './routes/govern.partners'
import { Route as GovernExchangeRouteImport } from './routes/govern.exchange'
import { Route as GovernDiscussionsRouteImport } from './routes/govern.discussions'
import { Route as GovernAlignmentRouteImport } from './routes/govern.alignment'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationRoute = OptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernRoute = GovernRouteImport.update({
  id: '/govern',
  path: '/govern',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargebackRoute = ChargebackRouteImport.update({
  id: '/chargeback',
  path: '/chargeback',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernPartnersRoute = GovernPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => GovernRoute,
} as any)
const GovernExchangeRoute = GovernExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => GovernRoute,
} as any)
const GovernDiscussionsRoute = GovernDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => GovernRoute,
} as any)
const GovernAlignmentRoute = GovernAlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => GovernRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/assistant': typeof AssistantRoute
  '/chargeback': typeof ChargebackRoute
  '/cloud': typeof CloudRoute
  '/govern': typeof GovernRouteWithChildren
  '/optimization': typeof OptimizationRoute
  '/plugins': typeof PluginsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/workforce': typeof WorkforceRoute
  '/govern/alignment': typeof GovernAlignmentRoute
  '/govern/discussions': typeof GovernDiscussionsRoute
  '/govern/exchange': typeof GovernExchangeRoute
  '/govern/partners': typeof GovernPartnersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/assistant': typeof AssistantRoute
  '/chargeback': typeof ChargebackRoute
  '/cloud': typeof CloudRoute
  '/govern': typeof GovernRouteWithChildren
  '/optimization': typeof OptimizationRoute
  '/plugins': typeof PluginsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/workforce': typeof WorkforceRoute
  '/govern/alignment': typeof GovernAlignmentRoute
  '/govern/discussions': typeof GovernDiscussionsRoute
  '/govern/exchange': typeof GovernExchangeRoute
  '/govern/partners': typeof GovernPartnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/assistant': typeof AssistantRoute
  '/chargeback': typeof ChargebackRoute
  '/cloud': typeof CloudRoute
  '/govern': typeof GovernRouteWithChildren
  '/optimization': typeof OptimizationRoute
  '/plugins': typeof PluginsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/workforce': typeof WorkforceRoute
  '/govern/alignment': typeof GovernAlignmentRoute
  '/govern/discussions': typeof GovernDiscussionsRoute
  '/govern/exchange': typeof GovernExchangeRoute
  '/govern/partners': typeof GovernPartnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalies'
    | '/assistant'
    | '/chargeback'
    | '/cloud'
    | '/govern'
    | '/optimization'
    | '/plugins'
    | '/resources'
    | '/settings'
    | '/workforce'
    | '/govern/alignment'
    | '/govern/discussions'
    | '/govern/exchange'
    | '/govern/partners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalies'
    | '/assistant'
    | '/chargeback'
    | '/cloud'
    | '/govern'
    | '/optimization'
    | '/plugins'
    | '/resources'
    | '/settings'
    | '/workforce'
    | '/govern/alignment'
    | '/govern/discussions'
    | '/govern/exchange'
    | '/govern/partners'
  id:
    | '__root__'
    | '/'
    | '/anomalies'
    | '/assistant'
    | '/chargeback'
    | '/cloud'
    | '/govern'
    | '/optimization'
    | '/plugins'
    | '/resources'
    | '/settings'
    | '/workforce'
    | '/govern/alignment'
    | '/govern/discussions'
    | '/govern/exchange'
    | '/govern/partners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomaliesRoute: typeof AnomaliesRoute
  AssistantRoute: typeof AssistantRoute
  ChargebackRoute: typeof ChargebackRoute
  CloudRoute: typeof CloudRoute
  GovernRoute: typeof GovernRouteWithChildren
  OptimizationRoute: typeof OptimizationRoute
  PluginsRoute: typeof PluginsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  WorkforceRoute: typeof WorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimization': {
      id: '/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof OptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/govern': {
      id: '/govern'
      path: '/govern'
      fullPath: '/govern'
      preLoaderRoute: typeof GovernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chargeback': {
      id: '/chargeback'
      path: '/chargeback'
      fullPath: '/chargeback'
      preLoaderRoute: typeof ChargebackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/govern/partners': {
      id: '/govern/partners'
      path: '/partners'
      fullPath: '/govern/partners'
      preLoaderRoute: typeof GovernPartnersRouteImport
      parentRoute: typeof GovernRoute
    }
    '/govern/exchange': {
      id: '/govern/exchange'
      path: '/exchange'
      fullPath: '/govern/exchange'
      preLoaderRoute: typeof GovernExchangeRouteImport
      parentRoute: typeof GovernRoute
    }
    '/govern/discussions': {
      id: '/govern/discussions'
      path: '/discussions'
      fullPath: '/govern/discussions'
      preLoaderRoute: typeof GovernDiscussionsRouteImport
      parentRoute: typeof GovernRoute
    }
    '/govern/alignment': {
      id: '/govern/alignment'
      path: '/alignment'
      fullPath: '/govern/alignment'
      preLoaderRoute: typeof GovernAlignmentRouteImport
      parentRoute: typeof GovernRoute
    }
  }
}

interface GovernRouteChildren {
  GovernAlignmentRoute: typeof GovernAlignmentRoute
  GovernDiscussionsRoute: typeof GovernDiscussionsRoute
  GovernExchangeRoute: typeof GovernExchangeRoute
  GovernPartnersRoute: typeof GovernPartnersRoute
}

const GovernRouteChildren: GovernRouteChildren = {
  GovernAlignmentRoute: GovernAlignmentRoute,
  GovernDiscussionsRoute: GovernDiscussionsRoute,
  GovernExchangeRoute: GovernExchangeRoute,
  GovernPartnersRoute: GovernPartnersRoute,
}

const GovernRouteWithChildren =
  GovernRoute._addFileChildren(GovernRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomaliesRoute: AnomaliesRoute,
  AssistantRoute: AssistantRoute,
  ChargebackRoute: ChargebackRoute,
  CloudRoute: CloudRoute,
  GovernRoute: GovernRouteWithChildren,
  OptimizationRoute: OptimizationRoute,
  PluginsRoute: PluginsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  WorkforceRoute: WorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
